version: '3.3'

services:
  web:
    build: ./project
    command: python3 -m uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    env_file: .env
    environment:
      - ENVIRONMENT=dev
      - TESTING=0